"""update old models, add city model

Revision ID: 667460777ba6
Revises: 07f76b89513f
Create Date: 2024-09-12 13:20:09.385378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667460777ba6'
down_revision: Union[str, None] = '07f76b89513f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('food', sa.Column('rate', sa.Float(precision=2), nullable=False))
    op.alter_column('food', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('shop', sa.Column('rate', sa.Float(precision=2), nullable=False))
    op.add_column('shop', sa.Column('city', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shop', 'city', ['city'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shop', type_='foreignkey')
    op.drop_column('shop', 'city')
    op.drop_column('shop', 'rate')
    op.alter_column('food', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('food', 'rate')
    op.drop_table('city')
    # ### end Alembic commands ###
