"""update order table

Revision ID: 9426d388c1a3
Revises: b617d105ff59
Create Date: 2025-01-07 14:28:00.870752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9426d388c1a3'
down_revision: Union[str, None] = 'b617d105ff59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food', 'rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.add_column('order', sa.Column('food_id', sa.Integer(), nullable=False))
    op.drop_constraint('order_product_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'food', ['food_id'], ['id'])
    op.drop_column('order', 'product_id')
    op.alter_column('shop', 'rate',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'rate',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.add_column('order', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_product_id_fkey', 'order', 'shop', ['product_id'], ['id'])
    op.drop_column('order', 'food_id')
    op.alter_column('food', 'rate',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
